---

# Scan_Name:
#   ports: all, "-", 1-1000
#   ports:
#     - 21
#     - 22
#   scripts:
#     - ftp_script
#   script_args: >
#     script.arg='value',
#     script2.arg='value2'
#   scan_type: sS
#   out_type: oA
#   misc:
#     - --open
#     - -g53


all:
  ports: all
  scan: sS
  out: oA

SSH:
  ports:
    - 22
  scripts:
    - ssh_script
  script_args: >
    script.arg='value',
    script2.arg='value2'
  scan: sS
  out: oA